openapi: 3.0.1
info:
  title: Accessorial List Prices V1
  description: This API is intended to expose carrier list price data for accessorials.
  contact:
    email: tyler.lacks@cardinalhealth.com
  version: 1.0.0
servers:
- url: https://ofl-next-carrier-contract-resource-service.apps.cf.gc.cahcloud.net/v1
tags:
- name: Accessorial List Price
  description: Accessorial list price data.
paths:
  /accessorial-list-prices:
    get:
      tags:
      - Accessorial List Price
      summary: Retrieve specifc accessorial list prices.
      description: Retrieve specifc accessorial list prices based on accessorial,
        service level and pickup date.
      operationId: getAccessorialListPrice
      parameters:
      - name: code
        in: query
        description: Accessorial code
        required: true
        schema:
          type: string
      - name: descriptionCode
        in: query
        description: Accessorial description code
        required: true
        schema:
          type: string
      - name: serviceLevel
        in: query
        description: Service level for the shipment the accessorial pertains to
        required: true
        schema:
          type: string
      - name: pickupDate
        in: query
        description: Pickup date for the shipment with the accessorial
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessorialListPrice'
        404:
          description: No data found based on the values in the request.
          content: {}
        500:
          description: An internal server error occurred. Please contact the developer
            team for assistance.
          content: {}
components:
  schemas:
    AccessorialListPrice:
      type: object
      properties:
        id:
          type: string
          example: EDF027D6-A90E-425A-8001-EAE6A0F54C2F
        minPrice:
          type: number
          example: 0.0
        maxPrice:
          type: number
          example: 3.0
        price:
          type: number
          example: 3.0
        unitType:
          type: string
          example: package
        surchargeId:
          type: string
          example: 59814AE9-4E6D-4F4E-BC6D-245028B7173A
        specialValue:
          type: string
          example: 100,1.05
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
